var html = '<html id="page"><head> <title>Arduino | Ev Kontrol Sistemi</title> <meta content="width=device-width,minimum-scale=1.0" name="viewport"> <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"> <meta http-equiv="Content-Type" content="text/html; charset=Utf8"><link rel="stylesheet" type="text/css" href="https://www.you-mp3.net/test/arduino/arduino.cc3000.css"></head> <body style=" "> <div class="head-main"><div class="user-image logo"></div><h1>Arduino Web Server</h1><h4>Bu sayfada arduino üzerinden led kontrolü veya sıcaklık bilgisi gibi analog değerlerin okunmasını sağlayabilirsiniz.</h4></div><div class="body-main"><div class="nav-content-main"><div id="veri_cek" onclick="veriCekStart(this)" class="syn_buton">Sync Başlat</div><div id="aktar" onclick="Aktar(this)" class="syn_buton">Çıktı Al</div><div id="table_grap" onclick="TableSetOn(this)" class="syn_buton">Grafik</div><label class="durum-any-set"><span>Otomatik Başlat</span><div class="switch" id="auto_st" onclick="autoStartSave(this)"></div></label><label class="durum-any-set">Yenileme Hızı(sn) <input onclick="AutoInputValue(this)" type="number" step="0.5" value="5" name="shoe-size" class="ynl_in" id="yen_hiz"></label></div><div class="nav-main" id="sicaklik"><div class="nav-title"><div class="spinner"></div> Sıcaklık Bilgisi</div><div class="page_null">Henüz Veri Yok</div><div class="temp-page" id="lm35"></div><div class="error-main" id="error"></div></div>  <div class="nav-main"><div class="nav-title">Pot Bilgisi</div> <div class="pot-durum"><div id="set-pot">0 </div><div class="pot-progress" id="pt_prog"></div></div><div class="error-main" id="error"></div></div>  <div class="nav-main"><div class="nav-title">Led Kontrolü</div><div class="durum-page"> <div class="control-titles"><label>Durum</label> <label>Buton</label> </div><div class="control-main"><label class="durum-setting"><div class="led-status-ikon"><i class="led-status"></i></div></label><label class="led-switch durum-setting"><input type="checkbox" name="checkboxName" class="checkbox"> <div class="switch" id="led1" onclick="led_ac(this);"></div></label></div> </div><div class="error-main led" id="error_led"></div></div>  <div class="nav-table-main"><table class="highchart" data-graph-container-before="1" data-graph-type="spline" data-graph-line-shadow="0"><thead class="ust_bilgi"><tr><th>Saat</th><th>Sıcaklık (C°)</th></tr></thead><tbody class="data-setin-temp" id="temp_grap"></tbody></table><div class="syn_buton tbl-kpt" data-kapat="on_grap" onclick="kapat(this)">Kapat</div></div></div><div class="footer-main"> <div class="nav-title">Hazırlayanlar</div><div href="http://fb.me/hmz06967" onclick="Opens(this)" class="user-body"><div class="user-image hamza"></div><div class="user-title">Hamza Özkan</div></div></div>  </body> <body></body></html>';
document.getElementById("page").innerHTML= html;

var url =['arduino.cc3000.js','highcharts.js','jquery.highchartTable-min.js'];	 //kütüphaneye dahil edilen dosyalar.

for (var i = 0; i<url.length; i++) {
	script = document.createElement('script');
	script.src = url[i];
	script.type = 'text/javascript';
	document.getElementsByTagName('head')[0].appendChild(script);
}


